name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to blogademy.org Registry
        uses: docker/login-action@v1 
        with:
          registry: registry.blogademy.org
          username: ${{ secrets.BL_USERNAME }}
          password: ${{ secrets.BL_PASSWORD }}
      - 
        name: Build and push PG
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: dev/postgres
          push: true
          tags: registry.blogademy.org/pg_test:latest
 
